import { CallToAction } from "@/components/layout/call-to-action";
import { Container } from "@/components/layout/container";
import { Footer } from "@/components/layout/footer";
import { Header } from "@/components/layout/header";
import { ScrollUP } from "@/components/layout/scroll-up";
import { Toaster } from "@/components/ui/sonner";
import type { Metadata } from "next";
import { Dosis, Inter } from "next/font/google";
import "./globals.css";

const dosis = Dosis({
  variable: "--font-dosis",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Baral Brothers",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${dosis.variable} ${inter.className} antialiased`}>
        <Header />
        <Container>{children}</Container>
        <CallToAction />
        <Footer />
        <Toaster position="top-center" />
        <ScrollUP />
      </body>
    </html>
  );
}
